### ISSUE TITLE
Option to disable/enable the extension

### ISSUE THREAD

**Issue by Zettt** [javoire/dyslexia-friendly#12]
Right now this extension is always enabled after the installation. It would be neat to turn it off and on as needed.

**Comment by javoire** [comment]
Definitely, I will try to add that asap.

**Comment by javoire** [comment]
Available in the latest [version](https://github.com/javoire/dyslexia-friendly/releases/tag/1.0.0), which has been released in [Chrome Web Store](https://chrome.google.com/webstore/detail/dyslexia-friendly/miepjgfkkommhllbbjaedffcpkncboeo)
