### ISSUE TITLE
Ruler makes links unclickable on some pages

### ISSUE THREAD

**Issue by selfthinker** [javoire/dyslexia-friendly#18]
The ruler makes links unclickable on some pages because it overlaps the text and links closer to where the pointer is.
Example site where this is happening: https://alphagov.github.io/accessibility-personas/simone/

I suspect this happens because the ruler height is set in `em` while the top position is set in `px`.
I have fixed this locally by adding a `max-height: 20px;` but the better fix would be to make the JS for the top position aware of the `em` size and reposition itself accordingly. Or make the ruler height use `px`. Although that would mean it wouldn't fit the height of the text correctly, you could also re-calculate the `em` into `px` to fix that.

**Comment by selfthinker** [comment]
I will deploy a hack to fix this on that example site next week, so you won't experience it happening there after that. Unless you temporarily disable that hack via the browser's inspector.

**Comment by javoire** [comment]
Hi, thanks for your feedback! That's indeed a silly bug, thx for finding it, I made a fix here https://github.com/javoire/dyslexia-friendly/pull/19, hoping to ship it in a few days.

Cheers!

**Comment by javoire** [comment]
fixed at https://github.com/javoire/dyslexia-friendly/blob/master/src/css/contentscript.css#L79

A new [version](https://github.com/javoire/dyslexia-friendly/releases/tag/1.0.0) has been released in Chrome Web Store
