### ISSUE TITLE
Make it look better in Dark Mode

### ISSUE THREAD

**Issue by javoire** [javoire/dyslexia-friendly#58]
E.g invert font and background colors

**Comment by phoenixeliot** [comment]
An example, github gets broken really badly when in dark mode.

Normal dark mode:
<img width="1753" alt="Screen Shot 2023-03-05 at 22 21 17" src="https://user-images.githubusercontent.com/491376/223012224-fb08f711-1678-41c0-9336-8c161c9b9918.png">


With DyslexiaFriendly:
<img width="1753" alt="Screen Shot 2023-03-05 at 22 21 23" src="https://user-images.githubusercontent.com/491376/223012232-5e59f75a-83f7-4454-a197-8ffdf2dcf4aa.png">

**Comment by sheady** [comment]
bumping this issue, I've had to disable dark mode on a site I like.
